{{- /*
Unified Secret for Yao-Oracle configuration with sensitive data.
This Secret contains:
- config-with-secrets.json: Complete configuration including namespaces with API keys and dashboard credentials
- Loaded directly by services via Kubernetes API (no file mounting)
- Watched by Kubernetes Informer for hot reload
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yao-oracle.fullname" . }}-secret
  labels:
    {{- include "yao-oracle.labels" . | nindent 4 }}
  annotations:
    description: "Yao-Oracle configuration with sensitive data (API keys, passwords)"
type: Opaque
stringData:
  # Complete configuration with sensitive data
  # Services read this directly from Kubernetes API using InClusterConfig()
  config-with-secrets.json: |
    {
      "proxy": {
        "namespaces": [
          {{- range $index, $namespace := .Values.config.namespaces }}
          {{- if $index }},{{ end }}
          {
            "name": {{ $namespace.name | quote }},
            "apikey": {{ $namespace.apikey | quote }},
            "description": {{ $namespace.description | default "" | quote }}
            {{- if $namespace.maxMemoryMB }},
            "maxMemoryMB": {{ $namespace.maxMemoryMB }}
            {{- end }}
            {{- if $namespace.maxKeys }},
            "maxKeys": {{ $namespace.maxKeys }}
            {{- end }}
            {{- if $namespace.defaultTTL }},
            "defaultTTL": {{ $namespace.defaultTTL }}
            {{- end }}
            {{- if $namespace.rateLimitQPS }},
            "rateLimitQPS": {{ $namespace.rateLimitQPS }}
            {{- end }}
          }
          {{- end }}
        ]
      },
      "dashboard": {
        "password": {{ .Values.config.dashboard.password | quote }},
        "jwtSecret": {{ .Values.config.dashboard.jwtSecret | default "change-me-jwt-secret" | quote }},
        "refreshInterval": {{ .Values.config.dashboard.refreshInterval | default 5 }},
        "authEnabled": {{ .Values.config.dashboard.authEnabled | default true }},
        "sessionTimeout": {{ .Values.config.dashboard.sessionTimeout | default 30 }}
      }
    }

